### ISSUE TITLE
To-Do list for publishing

### ISSUE THREAD

**Issue by vv-monsalve** [fridamedrano/Kalnia-Glaze#2]
- [x] Add details on the Color concept (combined the gradients + chosen palette) to the README.md file
- [x] Defining a name to replace the "Color" particle and meaningful to the concept of the font
- [x] ~~When adding the gradients, ensure consistency and compatibility across:~~
- [x] Try out #1 
    - [x] Include Simon and Laurence to repo
